services:
  db:
    image: postgres:18
    environment:
      POSTGRES_DB: sentinel
      POSTGRES_USER: vishalkumar
      POSTGRES_PASSWORD: sentinel
    volumes:
      - postgres_data:/var/lib/postgresql
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U vishalkumar -d sentinel"]
      interval: 5s
      timeout: 5s
      retries: 5

  api:
    build: .
    ports:
      - "8000:8000"
    environment:
      DATABASE_URL: postgresql://vishalkumar:sentinel@db:5432/sentinel
    depends_on:
      db:
        condition: service_healthy

volumes:
  postgres_data: