"""align logs nullability

Revision ID: f12a16fc1aeb
Revises: 
Create Date: 2026-09-15 21:59:27.841024

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'f12a16fc1aeb'
down_revision: Union[str, Sequence[str], None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('logs', 'level',
               existing_type=sa.VARCHAR(),
               nullable=False)
    op.alter_column('logs', 'service',
               existing_type=sa.VARCHAR(),
               nullable=False)
    op.alter_column('logs', 'message',
               existing_type=sa.VARCHAR(),
               nullable=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('logs', 'message',
               existing_type=sa.VARCHAR(),
               nullable=True)
    op.alter_column('logs', 'service',
               existing_type=sa.VARCHAR(),
               nullable=True)
    op.alter_column('logs', 'level',
               existing_type=sa.VARCHAR(),
               nullable=True)
    # ### end Alembic commands ###
